export interface CarOffer {
  id: string;
  created_at: string;
  advert_id: string;
  advert_url: string | null;
  status: string | null;
  offer_published: string | null;
  brand: string | null;
  model: string | null;
  model_version: string | null;
  year: number | null;
  price: number | null;
  vat_invoice: boolean | null;
  generation: string | null;
  new_used: string | null;
  body_type: string | null;
  mileage: number | null;
  fuel_type: string | null;
  engine_power: string | null;
  transmission: string | null;
  color: string | null;
  colour_type: string | null;
  country_origin: string | null;
  no_accident: boolean | null;
  technical_spec: Record<string, any> | null;
  features: Record<string, any> | null;
  main_photo_url: string | null;
  additional_photos: string[] | null;
  description: string | null;
  seller_type: string | null;
  seller_id: string | null;
  seller_name: string | null;
  seller_address: string | null;
  seller_city: string | null;
  seller_region: string | null;
  seller_country: string | null;
  seller_postal_code: string | null;
  google_maps_url: string | null;
}
